[theme]

# Primary accent for interactive elements
primaryColor = '#C7F4C2'

# Background color for the main content area
backgroundColor = '#FBFAF3'

# Background color for sidebar and most interactive widgets
secondaryBackgroundColor = '#0BAB7C'

# Color used for almost all text
textColor = '#151921'

# Font family for all text in the app, except code blocks
# Accepted values (serif | sans serif | monospace) 
# Default: "sans serif"
font = "sans serif"